### ISSUE TITLE
Backspace no longer works in textarea fields since version 0.60.0 update

### ISSUE THREAD

**Issue by gitman0** [noctarius/chromebackspaceonlinux#39]
Any textarea element on any website no longer has a functional backspace after receiving the 0.60.0 update. This includes github - I am unable to backspace on this very ticket.

Using Chrome 38 / Linux 3.11.10

**Comment by ghost** [comment]
the same for me :/
infos about the system: 
chromium Version 48.0.2564.116 | Ubuntu 15.10 (64-bit) 4.2.0-30-generic #36-Ubuntu SMP Fri Feb 26 00:58:07 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by c2h5oh** [comment]
same problem. had to disable the extension

**Comment by alextoind** [comment]
I can't even use the backspace when writing this message... Please fix it.

Google Chrome 48.0.2564.116 (64-bit) on Ubuntu 14.04 (64-bit), kernel 3.13.0-79-generic.

**Comment by rbarkhouse** [comment]
Same problem here, sorry had to uninstall :(

**Comment by noctarius** [comment]
Still happening with version 1.0.2?

PS: Sorry about that, missed that field type =(

**Comment by alextoind** [comment]
@noctarius it seems to be fine right now, thanks!

**Comment by gitman0** [comment]
that resolved it for me, thanks

question on version number - 1.0.2 is what it shows in the Extensions menu, but 0.60.0 is what it shows in the changelog in the extension's options menu. which version number should we use if reporting a problem?

**Comment by noctarius** [comment]
Oops the extensions version is correct, will fix changelog next time
